modLoader="javafml"
loaderVersion="[39,)"
license="MIT"

[[mods]]
  modId         = "onastick"
  version       = "${file.jarVersion}"
  displayName   = "On A Stick"
  displayURL    = "https://curseforge.com/minecraft/mc-mods/onastick-forge"
  logoFile      = "icon.png"
  authors       = "andante."

  description   = "Adds things on sticks."

[[dependencies.onastick]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.onastick]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"
